name: Copy Code to Another Repository

on:
  push:
    branches:
      - temp
jobs:
  copy-code:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "dokoh60689@dusyum.com"
          git config --global user.name "Democopy"

      # - name: Clone second repository
      #   run: |
      #     git clone https://Democopy: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@github.com/Democopy/Testcopy.git
      #     cd Testcopy

      - name: Copy code to second repository
        run: |
          git clone https://github.com/Democopy/Testcopy.git
          cd Testcopy
          cp -R $GITHUB_WORKSPACE/. $HOME/Testcopy/
          cd $HOME/Testcopy
          git switch -c demo
          git remote add origin2 https://github.com/Democopy/Testcopy.git
          git config user.email "dokoh60689@dusyum.com"
          git config user.name "Democopy"
          git rm -rf README.md
          git add .
          git commit -m "new"
          git pull origin main --ff --allow-unrelated-histories
          git push origin2 HEAD:demo

      # - name: Commit and push changes
        # env:
        #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        # run: |
        #   cd $HOME/Testcopy
        #   git commit -m "Copy code from temp branch"
        #   git remote set-url origin https://github.com/Democopy/Testcopy.git
        #   git push origin -u demo
