name: Copy Code to Another Repository

on:
  push:
    branches:
      - temp

jobs:
  copy-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Husnain0092"
          git config --global user.email "husnain.ibrahim.12@gmail.com"

      - name: Clone second repository
        run: |
          git clone https://Husnain0092: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@github.com/Democopy/Testcopy.git
          cd Testcopy
          git switch -c demo

      - name: Copy code to second repository
        run: |
          cp -R $GITHUB_WORKSPACE/. $HOME/Testcopy/
          cd $HOME/Testcopy
          git add .

      - name: Commit and push changes
        env:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          cd $HOME/Testcopy
          git commit -m "Copy code from temp branch"
          git remote set-url origin https://github.com/Democopy/Testcopy.git
          git push origin -u demo
