name: Copy Code to Another Repository

on:
  push:
    branches:
      - temp

jobs:
  copy-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Husnain0092"
          git config --global user.email "husnain.ibrahim.12@gmail.com"

      - name: Clone second repository
        run: |
          git clone https://Democopy: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@github.com/Democopy/Testcopy.git
          cd Testcopy

      - name: Copy code to second repository
        run: |
          cp -R $GITHUB_WORKSPACE/. $HOME/Testcopy/
          cd $HOME/Testcopy
          rm -rf .git
          git init
          git config --global user.name "Husnain0092"
          git config --global user.email "husnain.ibrahim.12@gmail.com"
          git add .
          git commit -m "latest"
          git remote add origin https://github.com/Democopy/Testcopy.git
          git switch -c demo
          git rm -rf README.md
          git add .
          git commit -m "new"
          git pull origin main --ff --allow-unrelated-histories
          git push -u origin demo

      # - name: Commit and push changes
        # env:
        #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        # run: |
        #   cd $HOME/Testcopy
        #   git commit -m "Copy code from temp branch"
        #   git remote set-url origin https://github.com/Democopy/Testcopy.git
        #   git push origin -u demo
