name: Copy Branch

on:
  push:
    branches:
      - temp

jobs:
  copy_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3

      - name: Copy branch
      
        run: |
          cd /home/runner/work
          git clone https://Seconddemo:${{ secrets.PAT }}@github.com/Seconddemo/Test.git
          cd Test
          ls -la /home/runner/work/sample-app/sample-app
          # git checkout -B main
          shopt -s dotglob
          cp -R /home/runner/work/sample-app/sample-app/* /home/runner/work/Test
          shopt -u dotglob
          # rsync -av --exclude="Test" /home/runner/work/sample-app/sample-app/* /home/runner/work/Test 
          cd /home/runner/work/Test
          ls -la /home/runner/work/Test
          git remote set-url --add origin https://github.com/Seconddemo/Test.git
          git config --global user.name "Seconddemo"
          git config --global user.email "somad56045@gienig.com"
          # git init
          # git remote add origin https://github.com/Seconddemo/Test.git
          git add .
          # git commit -m "first" || true
          git switch -c demo_new
          git pull origin main
          git push https://Seconddemo:${{ secrets.PAT }}@github.com/Seconddemo/Test.git demo_new
          
