name: Final Copy

on:
  push:
    branches:
      - temp

jobs:
  copy_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3

      - name: Copy branch
      
        run: |
          cd /home/runner/work/
          git clone https://Seconddemo:${{ secrets.PAT }}@github.com/Seconddemo/Test.git
          cd Test
          ls -la /home/runner/work/sample-app/
          # git checkout -B main
          cp -R /home/runner/work/sample-app/* /home/runner/work/Test 
          # rsync -av /home/runner/work/sample-app/sample-app /home/runner/work/Test 
          rm -rf /home/runner/work/Test/sample-app/.git
          cd /home/runner/work/Test/sample-app
          git remote set-url --add origin https://github.com/Seconddemo/Test.git
          
          # git init
          # git remote add origin https://github.com/Seconddemo/Test.git
          git config --global user.name "Seconddemo"
          git config --global user.email "somad56045@gienig.com"
          git add .
          git commit -m "first"
          git switch -c demo_new
          git config --global user.name "Husnain0092"
          git config --global user.email "husnain.ibrahim.12@gmail.com"
          git pull https://Husnain0092:${{ secrets.PAT1 }}@github.com/Husnain0092/sample-app.git temp --ff --allow-unrelated-histories
          git config --global user.name "Seconddemo"
          git config --global user.email "somad56045@gienig.com"
          git push https://Seconddemo:${{ secrets.PAT }}@github.com/Seconddemo/Test.git demo_new
          
